"""media items

Revision ID: 29b0142b86ed
Revises: cda4f3f92a95
Create Date: 2026-09-25 11:06:33.826857
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29b0142b86ed'
down_revision: Union[str, None] = 'cda4f3f92a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=60), nullable=True),
    sa.Column('aspect', sa.String(length=10), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_media_items_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_items'))
    )
    op.create_index(op.f('ix_media_items_owner_id'), 'media_items', ['owner_id'], unique=False)
    op.create_index('ix_media_owner_created', 'media_items', ['owner_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_owner_created', table_name='media_items')
    op.drop_index(op.f('ix_media_items_owner_id'), table_name='media_items')
    op.drop_table('media_items')
    # ### end Alembic commands ###
