"""job concurrency limit

Revision ID: 89c637411250
Revises: 9fc6bae3aaed
Create Date: 2026-09-25 16:04:08.902874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '89c637411250'
down_revision: Union[str, None] = '9fc6bae3aaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('max_concurrent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'max_concurrent')
    # ### end Alembic commands ###
