"""production platform: sessions, security, legal, notifications, usage

Revision ID: 9fc6bae3aaed
Revises: 3c1e7a9d2b10
Create Date: 2026-09-25 15:35:31.604201
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9fc6bae3aaed'
down_revision: Union[str, None] = '3c1e7a9d2b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('provider', name=op.f('pk_provider_health'))
    )
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analytics_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_events'))
    )
    op.create_index('ix_analytics_name_created', 'analytics_events', ['name', 'created_at'], unique=False)
    op.create_index('ix_analytics_user_created', 'analytics_events', ['user_id', 'created_at'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_table('api_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_requests_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_api_requests_request_id'))
    )
    op.create_index('ix_api_requests_created', 'api_requests', ['created_at'], unique=False)
    op.create_index('ix_api_requests_route_created', 'api_requests', ['route', 'created_at'], unique=False)
    op.create_index('ix_api_requests_user_created', 'api_requests', ['user_id', 'created_at'], unique=False)
    op.create_table('email_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_outbox_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_outbox'))
    )
    op.create_index(op.f('ix_email_outbox_created_at'), 'email_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_email_outbox_user_id'), 'email_outbox', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('user_id', 'key', name=op.f('uq_idempotency_keys_user_id'))
    )
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary_of_changes', sa.Text(), nullable=True),
    sa.Column('requires_acceptance', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_legal_documents_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_documents')),
    sa.UniqueConstraint('document_type', 'version', name=op.f('uq_legal_documents_document_type'))
    )
    op.create_index(op.f('ix_legal_documents_created_at'), 'legal_documents', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'dedupe_key', name=op.f('uq_notifications_user_id'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_security_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_request_id'), 'security_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_index('ix_security_type_created', 'security_events', ['type', 'created_at'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_support_tickets_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_tickets')),
    sa.UniqueConstraint('number', name=op.f('uq_support_tickets_number'))
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('trial_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trial_grants_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trial_grants')),
    sa.UniqueConstraint('email_hash', name=op.f('uq_trial_grants_email_hash'))
    )
    op.create_index(op.f('ix_trial_grants_created_at'), 'trial_grants', ['created_at'], unique=False)
    op.create_table('user_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_user_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notes'))
    )
    op.create_index(op.f('ix_user_notes_created_at'), 'user_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notes_user_id'), 'user_notes', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('browser', sa.String(length=60), nullable=True),
    sa.Column('os', sa.String(length=60), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], name=op.f('fk_ticket_messages_ticket_id_support_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_messages'))
    )
    op.create_index(op.f('ix_ticket_messages_created_at'), 'ticket_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.add_column('ai_usage', sa.Column('request_id', sa.String(length=40), nullable=True))
    op.add_column('ai_usage', sa.Column('error_code', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_ai_usage_request_id'), 'ai_usage', ['request_id'], unique=False)
    op.add_column('audit_logs', sa.Column('target_type', sa.String(length=40), nullable=True))
    op.add_column('audit_logs', sa.Column('target_id', sa.String(length=200), nullable=True))
    op.add_column('audit_logs', sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=400), nullable=True))
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target'), 'audit_logs', ['target'], unique=False)
    op.add_column('consents', sa.Column('document_id', sa.UUID(), nullable=True))
    op.add_column('consents', sa.Column('method', sa.String(length=40), nullable=True))
    op.add_column('consents', sa.Column('source', sa.String(length=40), nullable=True))
    op.add_column('consents', sa.Column('ip', sa.String(length=64), nullable=True))
    op.add_column('consents', sa.Column('user_agent', sa.String(length=400), nullable=True))
    op.create_index(op.f('ix_consents_kind'), 'consents', ['kind'], unique=False)
    op.create_foreign_key(op.f('fk_consents_document_id_legal_documents'), 'consents', 'legal_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.add_column('credit_ledger', sa.Column('event_type', sa.String(length=30), nullable=False, server_default='CREDIT_USAGE'))
    op.add_column('credit_ledger', sa.Column('resource_type', sa.String(length=40), nullable=True))
    op.add_column('credit_ledger', sa.Column('resource_id', sa.String(length=80), nullable=True))
    op.add_column('credit_ledger', sa.Column('provider_cost_usd', sa.Float(), nullable=True))
    op.add_column('credit_ledger', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('credit_ledger', sa.Column('request_id', sa.String(length=40), nullable=True))
    op.add_column('credit_ledger', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.create_index(op.f('ix_credit_ledger_ref'), 'credit_ledger', ['ref'], unique=False)
    op.create_index(op.f('ix_credit_ledger_request_id'), 'credit_ledger', ['request_id'], unique=False)
    op.create_foreign_key(op.f('fk_credit_ledger_actor_id_users'), 'credit_ledger', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.add_column('generation_jobs', sa.Column('credits_reserved', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('generation_jobs', sa.Column('request_id', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_generation_jobs_request_id'), 'generation_jobs', ['request_id'], unique=False)
    op.add_column('payments', sa.Column('invoice_id', sa.String(length=120), nullable=True))
    op.add_column('payments', sa.Column('subscription_ref', sa.String(length=120), nullable=True))
    op.add_column('payments', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    op.add_column('subscriptions', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('price_aed', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('uploaded_files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('admin_role', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('signup_source', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('signup_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('users', sa.Column('referral_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('suspended_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_unique_constraint(op.f('uq_users_referral_code'), 'users', ['referral_code'])
    op.create_foreign_key(op.f('fk_users_referred_by_id_users'), 'users', 'users', ['referred_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('webhook_events', sa.Column('payload_hash', sa.String(length=64), nullable=True))
    op.add_column('webhook_events', sa.Column('status', sa.String(length=20), nullable=False, server_default='received'))
    op.add_column('webhook_events', sa.Column('result', sa.String(length=40), nullable=True))
    op.add_column('webhook_events', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('webhook_events', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # --- data: existing admins become super admins; ledger rows get event types; old webhooks were processed
    op.execute("UPDATE users SET admin_role = 'super_admin' WHERE role = 'admin' AND admin_role IS NULL")
    op.execute("UPDATE users SET email_verified_at = created_at WHERE email_verified AND email_verified_at IS NULL")
    op.execute("""UPDATE credit_ledger SET event_type = CASE
        WHEN amount < 0 THEN 'CREDIT_USAGE'
        WHEN reason LIKE 'media_pack:%' THEN 'CREDIT_PURCHASE'
        WHEN reason LIKE 'admin_grant%' THEN 'CREDIT_ADMIN_GRANT'
        WHEN reason LIKE '%refund%' THEN 'CREDIT_REFUND'
        ELSE 'CREDIT_ADJUSTMENT' END""")
    op.execute("UPDATE webhook_events SET status = CASE WHEN processed_at IS NULL THEN 'received' ELSE 'processed' END")

    # --- append-only evidence: audit logs and consent records cannot be edited or deleted.
    # A legally required purge must set `SET LOCAL app.allow_evidence_purge = 'on'` in its transaction.
    op.execute("""
    CREATE OR REPLACE FUNCTION forbid_evidence_change() RETURNS trigger AS $$
    BEGIN
      IF current_setting('app.allow_evidence_purge', true) = 'on' THEN
        RETURN COALESCE(NEW, OLD);
      END IF;
      -- ON DELETE SET NULL of the acting user is the only update allowed.
      IF TG_OP = 'UPDATE' AND TG_TABLE_NAME = 'audit_logs'
         AND ROW(NEW.action, NEW.target, NEW.details, NEW.before, NEW.after, NEW.reason, NEW.created_at)
             IS NOT DISTINCT FROM ROW(OLD.action, OLD.target, OLD.details, OLD.before, OLD.after, OLD.reason, OLD.created_at)
      THEN
        RETURN NEW;
      END IF;
      RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
    END $$ LANGUAGE plpgsql;
    """)
    for table in ("audit_logs", "consents"):
        op.execute(f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
                   f"FOR EACH ROW EXECUTE FUNCTION forbid_evidence_change()")


def downgrade() -> None:
    for table in ("audit_logs", "consents"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_evidence_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_events', 'error_message')
    op.drop_column('webhook_events', 'retry_count')
    op.drop_column('webhook_events', 'result')
    op.drop_column('webhook_events', 'status')
    op.drop_column('webhook_events', 'payload_hash')
    op.drop_constraint(op.f('fk_users_referred_by_id_users'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_referral_code'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'deletion_requested_at')
    op.drop_column('users', 'suspended_reason')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'signup_meta')
    op.drop_column('users', 'signup_source')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'admin_role')
    op.drop_column('uploaded_files', 'deleted_at')
    op.drop_column('subscriptions', 'price_aed')
    op.drop_column('subscriptions', 'canceled_at')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'subscription_ref')
    op.drop_column('payments', 'invoice_id')
    op.drop_index(op.f('ix_generation_jobs_request_id'), table_name='generation_jobs')
    op.drop_column('generation_jobs', 'request_id')
    op.drop_column('generation_jobs', 'credits_reserved')
    op.drop_constraint(op.f('fk_credit_ledger_actor_id_users'), 'credit_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_credit_ledger_request_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_ref'), table_name='credit_ledger')
    op.drop_column('credit_ledger', 'meta')
    op.drop_column('credit_ledger', 'request_id')
    op.drop_column('credit_ledger', 'actor_id')
    op.drop_column('credit_ledger', 'provider_cost_usd')
    op.drop_column('credit_ledger', 'resource_id')
    op.drop_column('credit_ledger', 'resource_type')
    op.drop_column('credit_ledger', 'event_type')
    op.drop_constraint(op.f('fk_consents_document_id_legal_documents'), 'consents', type_='foreignkey')
    op.drop_index(op.f('ix_consents_kind'), table_name='consents')
    op.drop_column('consents', 'user_agent')
    op.drop_column('consents', 'ip')
    op.drop_column('consents', 'source')
    op.drop_column('consents', 'method')
    op.drop_column('consents', 'document_id')
    op.drop_index(op.f('ix_audit_logs_target'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'after')
    op.drop_column('audit_logs', 'before')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'target_type')
    op.drop_index(op.f('ix_ai_usage_request_id'), table_name='ai_usage')
    op.drop_column('ai_usage', 'error_code')
    op.drop_column('ai_usage', 'request_id')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_created_at'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_notes_user_id'), table_name='user_notes')
    op.drop_index(op.f('ix_user_notes_created_at'), table_name='user_notes')
    op.drop_table('user_notes')
    op.drop_index(op.f('ix_trial_grants_created_at'), table_name='trial_grants')
    op.drop_table('trial_grants')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_security_type_created', table_name='security_events')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_request_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_legal_documents_created_at'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_email_outbox_user_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_created_at'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index('ix_api_requests_user_created', table_name='api_requests')
    op.drop_index('ix_api_requests_route_created', table_name='api_requests')
    op.drop_index('ix_api_requests_created', table_name='api_requests')
    op.drop_table('api_requests')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_analytics_user_created', table_name='analytics_events')
    op.drop_index('ix_analytics_name_created', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_table('provider_health')
    # ### end Alembic commands ###
